sulu_tag_api:
    resource: "@SuluTagBundle/Resources/config/routing_api.yaml"
    prefix: /admin/api

sulu_admin:
    resource: "@SuluAdminBundle/Resources/config/routing.yaml"
    prefix: /admin

sulu_admin_api:
    resource: "@SuluAdminBundle/Resources/config/routing_api.yaml"
    prefix: /admin/api

sulu_contact_api:
    resource: "@SuluContactBundle/Resources/config/routing_api.yaml"
    prefix: /admin/api

sulu_security:
    resource: "@SuluSecurityBundle/Resources/config/routing.yaml"
    prefix: /admin/security

sulu_security_api:
    resource: "@SuluSecurityBundle/Resources/config/routing_api.yaml"
    prefix: /admin/api

sulu_route_api:
    resource: "@SuluRouteBundle/config/routing_admin_api.yaml"
    prefix: /admin/api

sulu_page_api:
    resource: "@SuluPageBundle/config/routing_admin_api.yaml"
    prefix: /admin/api

sulu_search_api:
    resource: "@SuluSearchBundle/config/routing_admin_api.yaml"
    prefix: /admin/api

sulu_media:
    resource: "@SuluMediaBundle/Resources/config/routing.yaml"
    prefix: /admin/media

sulu_media_website:
    resource: "@SuluMediaBundle/Resources/config/routing_website.yaml"

sulu_media_api:
    resource: "@SuluMediaBundle/Resources/config/routing_api.yaml"
    prefix: /admin/api

sulu_category_api:
    resource: "@SuluCategoryBundle/Resources/config/routing_api.yaml"
    prefix: /admin/api

sulu_snippet_api:
    resource: "@SuluSnippetBundle/config/routing_admin_api.yaml"
    prefix: /admin/api

sulu_location:
    resource: "@SuluLocationBundle/Resources/config/routing.yaml"
    prefix: /admin/location

sulu_website:
    resource: "@SuluWebsiteBundle/Resources/config/routing.yaml"
    prefix: /admin/website

sulu_website_api:
    resource: "@SuluWebsiteBundle/Resources/config/routing_api.yaml"
    prefix: /admin/api

sulu_preview:
    resource: "@SuluPreviewBundle/Resources/config/routing.yaml"
    prefix: /admin/preview

sulu_preview_api:
    resource: "@SuluPreviewBundle/Resources/config/routing_api.yaml"
    prefix: /admin/api

sulu_preview_public:
    resource: "@SuluPreviewBundle/Resources/config/routing_public.yaml"
    prefix: /admin/p

sulu_activity_api:
    resource: "@SuluActivityBundle/Resources/config/routing_api.yaml"
    prefix: /admin/api

sulu_trash_api:
    resource: "@SuluTrashBundle/Resources/config/routing_api.yaml"
    prefix: /admin/api

sulu_reference_api:
    resource: "@SuluReferenceBundle/Resources/config/routing_api.yaml"
    prefix: /admin/api

sulu_article_api:
    resource: "@SuluArticleBundle/config/routing_admin_api.yaml"
    prefix: /admin/api

sulu_custom_url_api:
    resource: "@SuluCustomUrlBundle/config/routing_admin_api.yaml"
    prefix: /admin/api

# to enable audience targeting see: https://docs.sulu.io/en/2.6/bundles/audience_targeting.html
#sulu_audience_targeting_api:
#    resource: "@SuluAudienceTargetingBundle/Resources/config/routing_api.yaml"
#    prefix: /admin/api
